version: "3.9"

services:
  backend:
    build:
      context: .           
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app/apps/backend

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend
